name: Draft release notes

on:
  pull_request_target:
    types: [closed]

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: salsita/release-drafter@master
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
