name: Run CI lint and tests on every PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  Test:
    name: Lint and test

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2

    - name: Install Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Yarn install
      run: yarn --frozen-lockfile

    - name: Yarn build
      run: yarn build

    - name: Lint
      run: yarn lint --max-warnings=0

    - name: Test
      run: yarn test
