name: Build, test and release to NPM

on:
  push:
    tags:
      - v[0-9]*

jobs:

  deploy:
    name: Build, test and release to NPM
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Setup variables
        run: |
          GITHUB_TAG=$(echo "$GITHUB_REF" | awk -F '/' '{print $3}')
          VERSION=$(echo "$GITHUB_TAG" | sed -e s/^v//)
          VERSION_TAG=$(echo "$VERSION" | egrep -o "^[0-9\.]+-[a-z]+[0-9\.]*$" | egrep -o [a-z]+ | cat)

          echo "::set-env name=GITHUB_TAG::$GITHUB_TAG"
          echo "::set-env name=VERSION::$VERSION"
          echo "::set-env name=VERSION_TAG::$VERSION_TAG"

      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Yarn install
        run: yarn --frozen-lockfile

      - name: Yarn build
        run: yarn build

      - name: Check `package.json` versions
        run: yarn spicy check-version $VERSION

      - name: Test
        run: yarn test

      - name: Initiate NPM credentials
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Publish `utils` package
        working-directory: ./packages/utils
        run: npm publish --tag ${VERSION_TAG:=latest}

      - name: Publish `core` package
        working-directory: ./packages/core
        run: npm publish --tag ${VERSION_TAG:=latest}

      - name: Publish `observables` package
        working-directory: ./packages/observables
        run: npm publish --tag ${VERSION_TAG:=latest}
